### ISSUE TITLE
Please remove the 22 mb gif 😭

### ISSUE THREAD

**Issue by halilozercan** [godaddy/compose-color-picker#20]
Github cloning doesn't have much bandwidth. Cloning this repo with a 22mb gif took me 4-5 minutes. Can we move the gif somewhere else with a link or just convert it to mp4?

**Comment by riggaroo** [comment]
Hi @halilozercan, I've removed the files and removed them from history - replaced with videos that aren't stored in the repo.

I think Github takes a while to run gc, so it might still be downloading all of them when cloning at the moment. Will check back tomorrow to see if this is still the case - otherwise I'm potentially missing something from the git rewrite commands.

**Comment by halilozercan** [comment]
Thank you so much! I'll retry this evening and tomorrow.

**Comment by ffgiraldez** [comment]
@halilozercan I will close as no complaints for a long time, and it seems fixed.
